model:
  model_type: "DeepLabV3Plus"            # Model type (e.g., unet, deeplabv3)
  n_channels: 4                 # Number of input channels (e.g., RGB image has 3 channels)
  n_classes: 1                  # Number of output classes for the segmentation task
  conf_threshold: 0.75           # Confidence threshold for the segmentation task

training:
  wandb_project_name: 'building_comparison_DL'     # Name of the Weights & Biases project
  optim: 'adam'                 # Optimizer to use (e.g., adam, RMSprop)
  learning_rate: 2e-4           # Learning rate for the optimizer
  weight_decay: 1e-8            # Weight decay (L2 regularization)
  momentum: 0.999               # Momentum for optimizer (e.g., RMSprop or SGD)
  amp: false                    # Automatic Mixed Precision (True/False)
  reduce_lr_metric: 'train_loss'  # Metric to use for learning rate reduction
  reduce_lr_patience: 5         # Number of epochs to wait before reducing learning rate
  reduce_lr_factor: 0.5         # Factor to reduce learning rate by

  pl_settings:
    checkpoint_saving_metric: "train_loss"
    early_stop_metric: "train_loss"
    accelerator: 'cuda'
    devices:  [0]
    strategy: "ddp"
    check_val_every_n_epoch: 1 # has to be int
    log_every_n_steps: 50
    val_check_interval: 0.5 # float for percentage 0.25
    max_epochs: 1000
    limit_val_batches: 10
    continue_training: false # logs path
    load_weights_only: false # false, or ckpt path

data:
  dataset_type: "RS"            # ["fake", "RS"]
  bands: 4                      # Number of bands in the input image
  interpolation_size: 512       # Size of the interpolated image
  crop: True                    # Crop the image to the wanted size
  data_type: 'lr'               # Type of data to use (e.g., lr,sr,hr)
  no_workers: 16                # Number of workers for the DataLoader
  batch_size: 32                # Batch size for the DataLoader

