model:
  model_type: "new_unet"            # Model type (e.g., unet, deeplabv3)
  n_channels: 4                 # Number of input channels (e.g., RGB image has 3 channels)
  n_classes: 1                  # Number of output classes for the segmentation task
  conf_threshold: 0.75           # Confidence threshold for the segmentation task
  encoder: "se_resnext50_32x4d" #"se_resnext50_32x4d"  tu-hrnet_w48  # choose from https://smp.readthedocs.io/en/latest/encoders.html, only supported for smp models
  encoder_depth: 5
  decoder_channels: [512, 256, 128, 64, 32]
  decoder_use_norm: "batchnorm"
  decoder_attention_type: "scse"
  decoder_interpolation: "bilinear"
  use_aux_params: True

training:
  wandb_project_name: 'Samuel_building_segmentation'     # Name of the Weights & Biases project
  optim: 'adam'
  loss:
    fn: 'FocalLoss'     # Loss function to use (e.g., combined, BCEWithLogitsLoss, CrossEntropyLoss)
    a: 0.7
    b: 0.3
    g: 1.5
  learning_rate: 1e-4            # Learning rate for the optimizer
  weight_decay: 5e-5            # Weight decay (L2 regularization)
  momentum: 0.999               # Momentum for optimizer (e.g., RMSprop or SGD)
  amp: True                     # Automatic Mixed Precision (True/False)
  reduce_lr_metric: 'val_loss'  # Metric to use for learning rate reduction
  reduce_lr_patience: 5         # Number of epochs to wait before reducing learning rate
  reduce_lr_factor: 0.5         # Factor to reduce learning rate by
  early_stopping_patience: 10

  pl_settings:
    checkpoint_saving_metric: "val_loss"
    early_stop_metric: "val_loss"
    accelerator: 'cuda'
    devices:  [1]
    strategy: 'ddp_find_unused_parameters_true' #"ddp"
    check_val_every_n_epoch: 1 # has to be int
    log_every_n_steps: 100
    max_epochs: 100000
    limit_val_batches: 1000
    continue_training: False #"logs/building_comparison/2024-10-10_22-35-39/last.ckpt"
    load_weights_only: False #"logs/building_comparison_DL/2024-11-06_12-23-45/last.ckpt" # false, or ckpt path

data:
  dataset_type: "RS"            # ["fake", "RS"]
  dataset: "filtered"
  normalize: 'percentile'       # allows percentile normalisation
  bands: 4                      # Number of bands in the input image
  use_256_subsample: True       # select and crop a subsample of the image
  resample_512: False           # resample the cropped image to 512x512 again
  interpolate_lr: False
  lr_interpolation_type: 'bicubic' # Type of interpolation to use
  data_type: 'sr'               # Type of data to use (e.g., lr,sr,hr)
  no_workers: 16                # Number of workers for the DataLoader
  batch_size: 32                # Batch size for the DataLoader
  data_path: '/data/USERS/shollend/metadata/stratification_tables/'
  input_path: '/data/USERS/shollend/sentinel2/sr_inference/bilinear/'
  target_path: '/data/USERS/shollend/combined_download/output/hr_mask/'
  img_post: 'tif'
